blog_site_1/blog/urls.py
from django.urls import path
from . import views

from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

blog_site_1/blog_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog_site_1/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    ) # (A,B) = (Value which will be stored in the model, Value which will be displayed to the user as choice)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # Default manager
    published = PublishedManager() # Custom manager

    tags = TaggableManager()
    
    def get_absolute_url(self):
        return reverse(
            'blog:post_detail',
            args = [self.publish.year, self.publish.month, self.publish.day, self.slug]
        )

    class Meta:
        ordering = ('-publish',)
        db_table = 'blog_post' # Default table name is already 'blog_post'

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog_site_1/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog_site_1/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm

# Function-based View of Post List
def post_list(request, tag_slug=None):
    tag = None
    posts = Post.published.all()

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts, 5)
    curr_page = request.GET.get('page') # Used to retrieve the current page number
    
    try:
        posts = paginator.page(curr_page) # Would return the results of current page
    except PageNotAnInteger:
        posts = paginator.page(1) # Would return the first page of results
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) # Would return the last page of results
    
    return render(request, 'blog/post/list.html', {'posts': posts, 'page': curr_page, 'tag': tag})

"""
# Class-based View of Post List
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'
"""

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug = post,
        status = 'published',
        publish__year = year,
        publish__month = month,
        publish__day = day
    )
    # Using Comment model's [related_name='comments'] to extract all relevant comments
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create a new Comment object, but don't save it to the database yet
            new_comment = comment_form.save(commit=False)
            new_comment.post = post # Assign the current post to the comment
            new_comment.save() # Save the comment to the database
    else:
        # Displays a new instance of an empty form (request method is GET)
        comment_form = CommentForm()

    # List of similar posts (based on associated tags)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))
    similar_posts = similar_posts.order_by('-same_tags', '-publish')
    similar_posts = similar_posts[:5] # Retrieving only the first 5 posts

    context = {'post': post, 'comments': comments, 'new_comment': new_comment, 
    'comment_form': comment_form, 'similar_posts': similar_posts}
    
    return render(request, 'blog/post/detail.html', context)

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # A filled form is submitted, which needs to be processed
        form = EmailPostForm(data=request.POST)
        if form.is_valid():
            # Sends an e-mail, if the form is valid
            # If the form is invalid, then the template is loaded again using render()
            cd = form.cleaned_data # Creates a dictionary of form fields and its values 

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            
            send_mail(subject, message, 'somedummyid@gmail.com', [cd['to']])
            sent = True
    else:
        # Displays a new instance of an empty form (request method is GET)
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog_site_1/blog/templates/blog/base.html
{% load static %}
{% load block_tags %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2><b><u>Welcome to My Blog</u></b></h2>
            <p>
                Number of blogs I have written so far: {% total_posts %} <br>
                <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS Feed</a>
            </p>
            <hr>
            <h4>Latest Posts:</h4>
            {% show_latest_posts %}
            <hr>
            <div>
                <h4>Most Commented Posts</h4>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </body>
</html>

blog_site_1/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog_site_1/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load block_tags %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    <hr>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>

    <hr>

    <h2>Similar Posts:</h2>
    {% for sim_post in similar_posts %}
        <p>
            <a href="{{ sim_post.get_absolut_url }}">{{ sim_post.title }}</a>
        </p>
    {% empty %}
        <p>There are no similar posts.</p>
    {% endfor %}
    
    <hr>

    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
            <hr style="margin: 0px;">
        </div>
        {% empty %}
            <p>There are no comments in this post.</p>
    {% endfor %}

    {% if new_comment %}
        <h2 style="border: solid 1px green;">Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

blog_site_1/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog_site_1/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load block_tags %}

{% block title %}
    My Blog
{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    <hr><hr>
    
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">
        <!-- <b>Tags</b>: {{ post.tags.all|join:", " }} -->
        <b>Tags</b>:
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last%}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
        Published on {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    <hr>
    {% endfor %}

    <!-- When function-based view is used -->
    {% include 'blog/pagination.html' with page=posts %}

    <!-- When class-based view is used -->
    <!-- {% include 'blog/pagination.html' with page=page_obj %} -->
{% endblock %}

blog_site_1/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if sent %}
        <h1>E-mail Sent Successfully</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            <!-- or can use form.as_ol or form.as_table to render it accordingly -->
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}